<?php
//ARTS
$labels = array(
    'name'                  => _x( 'Arts', 'Post Type General Name', 'zacpt' ),
    'singular_name'         => _x( 'Art', 'Post Type Singular Name', 'zacpt' ),
    'menu_name'             => __( 'Arts', 'zacpt' ),
    'name_admin_bar'        => __( 'Arts', 'zacpt' ),
    'archives'              => __( 'Item Archives', 'zacpt' ),
    'attributes'            => __( 'Item Attributes', 'zacpt' ),
    'parent_item_colon'     => __( 'Parent Item:', 'zacpt' ),
    'all_items'             => __( 'All Items', 'zacpt' ),
    'add_new_item'          => __( 'Add New Item', 'zacpt' ),
    'add_new'               => __( 'Add New', 'zacpt' ),
    'new_item'              => __( 'New Item', 'zacpt' ),
    'edit_item'             => __( 'Edit Item', 'zacpt' ),
    'update_item'           => __( 'Update Item', 'zacpt' ),
    'view_item'             => __( 'View Item', 'zacpt' ),
    'view_items'            => __( 'View Items', 'zacpt' ),
    'search_items'          => __( 'Search Item', 'zacpt' ),
    'not_found'             => __( 'Not found', 'zacpt' ),
    'not_found_in_trash'    => __( 'Not found in Trash', 'zacpt' ),
    'featured_image'        => __( 'Featured Image', 'zacpt' ),
    'set_featured_image'    => __( 'Set featured image', 'zacpt' ),
    'remove_featured_image' => __( 'Remove featured image', 'zacpt' ),
    'use_featured_image'    => __( 'Use as featured image', 'zacpt' ),
    'insert_into_item'      => __( 'Insert into item', 'zacpt' ),
    'uploaded_to_this_item' => __( 'Uploaded to this item', 'zacpt' ),
    'items_list'            => __( 'Items list', 'zacpt' ),
    'items_list_navigation' => __( 'Items list navigation', 'zacpt' ),
    'filter_items_list'     => __( 'Filter items list', 'zacpt' ),
);
$args = array(
    'label'                 => __( 'Art', 'zacpt' ),
    'description'           => __( 'Arts', 'zacpt' ),
    'labels'                => $labels,
    'supports'              => array( 'title', 'editor', 'thumbnail', 'comments', 'trackbacks', 'revisions', 'custom-fields', 'page-attributes', 'post-formats' ),
    'taxonomies'            => array( 'category', 'post_tag' ),
    'hierarchical'          => false,
    'public'                => true,
    'show_ui'               => true,
    'show_in_menu'          => true,
    'menu_position'         => 5,
    'menu_icon'             => 'dashicons-art',
    'show_in_admin_bar'     => true,
    'show_in_nav_menus'     => true,
    'can_export'            => true,
    'has_archive'           => true,
    'exclude_from_search'   => false,
    'publicly_queryable'    => true,
    'capability_type'       => 'post',
    'show_in_rest'          => true,
);
register_post_type( 'arts', $args );
